// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:43 )

// Modules imports
import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { SynopsisService } from './../services/synopsis.service';

// Models imports
import { Synopsis } from '../synopsis.model';

@Component({
  selector: 'app-synopsis-list',
  templateUrl: './synopsis-list.component.html',
  styleUrls: ['./synopsis-list.component.css']
})
export class SynopsisListComponent implements OnInit {

  @ViewChild('deleteModal') deleteModal;
  private bookIdToDelete: number;

  private synopsisIdToDelete;

  private listOfSynopsiss: Synopsis[];
  private listId = 'SYNOPSIS_COMPONENT_LIST';

  private title = 'List of Synopsiss';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _synopsisService: SynopsisService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService) { }

  ngOnInit() {
    // On init get all Synopsiss
    this.getAllSynopsiss();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Synopsis list
    EmitterService.get(this.listId).subscribe((data: Synopsis[]) => this.getAllSynopsiss());
  }

  /**
   * Get all Synopsis using the service SynopsisService
   */
  getAllSynopsiss = (): void => {
    this._synopsisService.getAll().subscribe(
      (data: Synopsis[]) => {
        this.listOfSynopsiss = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editSynopsis = (bookId): void => {
    // Navigate to synopsis form component
    this._router.navigate(['./synopsis-form', bookId]);
  }

  openDeleteModal(bookId) {
    this.bookIdToDelete = bookId;
    this.deleteModal.open();
  }

  confirmDelete() {
    this._synopsisService.delete(this.bookIdToDelete).subscribe(
      result => {
        // Notify Synopsis list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The car synopsis with the id='${this.bookIdToDelete}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });

    this.deleteModal.close();
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfSynopsiss.length, page);

    // get current page of items
    this.pagedItems = this.listOfSynopsiss.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
