// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

// Modules imports
import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { CustomerService } from './../services/customer.service';

// Models imports
import { Customer } from '../customer.model';

@Component({
  selector: 'app-customer-list',
  templateUrl: './customer-list.component.html',
  styleUrls: ['./customer-list.component.css']
})
export class CustomerListComponent implements OnInit {

  @ViewChild('deleteModal') deleteModal;
  private codeToDelete: string;

  private customerIdToDelete;

  private listOfCustomers: Customer[];
  private listId = 'CUSTOMER_COMPONENT_LIST';

  private title = 'List of Customers';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _customerService: CustomerService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService) { }

  ngOnInit() {
    // On init get all Customers
    this.getAllCustomers();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Customer list
    EmitterService.get(this.listId).subscribe((data: Customer[]) => this.getAllCustomers());
  }

  /**
   * Get all Customer using the service CustomerService
   */
  getAllCustomers = (): void => {
    this._customerService.getAll().subscribe(
      (data: Customer[]) => {
        this.listOfCustomers = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editCustomer = (code): void => {
    // Navigate to customer form component
    this._router.navigate(['./customer-form', code]);
  }

  openDeleteModal(code) {
    this.codeToDelete = code;
    this.deleteModal.open();
  }

  confirmDelete() {
    this._customerService.delete(this.codeToDelete).subscribe(
      result => {
        // Notify Customer list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The car customer with the id='${this.codeToDelete}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });

    this.deleteModal.close();
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfCustomers.length, page);

    // get current page of items
    this.pagedItems = this.listOfCustomers.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
