// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:43 )

export interface Publisher {
	code: number; // Wrapper Type : Number
	countryCode: string; // Wrapper Type : String
	name: string; // Wrapper Type : String
	email: string; // Wrapper Type : String
	contact: string; // Wrapper Type : String
	city: string; // Wrapper Type : String
	zipCode: number; // Wrapper Type : Number
	phone: string; // Wrapper Type : String
}
