// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

export interface BookOrderItem {
	bookOrderId: number; // Wrapper Type : Number
	bookId: number; // Wrapper Type : Number
	quantity: number; // Wrapper Type : Number
	price: number; // Wrapper Type : Number
}
