// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:43 )

// Modules imports
import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { WorkgroupService } from './../services/workgroup.service';

// Models imports
import { Workgroup } from '../workgroup.model';

@Component({
  selector: 'app-workgroup-list',
  templateUrl: './workgroup-list.component.html',
  styleUrls: ['./workgroup-list.component.css']
})
export class WorkgroupListComponent implements OnInit {

  @ViewChild('deleteModal') deleteModal;
  private idToDelete: number;

  private workgroupIdToDelete;

  private listOfWorkgroups: Workgroup[];
  private listId = 'WORKGROUP_COMPONENT_LIST';

  private title = 'List of Workgroups';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _workgroupService: WorkgroupService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService) { }

  ngOnInit() {
    // On init get all Workgroups
    this.getAllWorkgroups();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Workgroup list
    EmitterService.get(this.listId).subscribe((data: Workgroup[]) => this.getAllWorkgroups());
  }

  /**
   * Get all Workgroup using the service WorkgroupService
   */
  getAllWorkgroups = (): void => {
    this._workgroupService.getAll().subscribe(
      (data: Workgroup[]) => {
        this.listOfWorkgroups = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editWorkgroup = (id): void => {
    // Navigate to workgroup form component
    this._router.navigate(['./workgroup-form', id]);
  }

  openDeleteModal(id) {
    this.idToDelete = id;
    this.deleteModal.open();
  }

  confirmDelete() {
    this._workgroupService.delete(this.idToDelete).subscribe(
      result => {
        // Notify Workgroup list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The car workgroup with the id='${this.idToDelete}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });

    this.deleteModal.close();
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfWorkgroups.length, page);

    // get current page of items
    this.pagedItems = this.listOfWorkgroups.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
