// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:43 )

export interface Workgroup {
	id: number; // Wrapper Type : Number
	name: string; // Wrapper Type : String
	description: string; // Wrapper Type : String
	creationDate: Date; // Wrapper Type : Date
}
