// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit, ViewChild } from '@angular/core';

// Models and services imports
import { Customer } from './../customer.model';
import { CustomerService } from './../services/customer.service';
import { Country } from './../../country/country.model';
import { CountryService } from './../../country/services/country.service';
import * as _ from 'underscore';
import { BsDatepickerConfig } from 'ngx-bootstrap/datepicker';

@Component({
  selector: 'app-customer-form',
  templateUrl: './customer-form.component.html',
  styleUrls: ['./customer-form.component.css']
})
export class CustomerFormComponent implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  @ViewChild('deleteModal') deleteModal;

  private title = 'Customer Form';
  private customer: Customer;
  private form: FormGroup;
  private ids;

  private bsConfig: Partial<BsDatepickerConfig>;

  // Country Select
  private countrysData: Country[];

  constructor(
    private _countryService: CountryService,
    private _customerService: CustomerService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService) {

    this.bsConfig = Object.assign({}, { containerClass: 'theme-dark-blue' });
  }

  ngOnInit() {
    this.getIdFromRouteParams();
    this.fetchCountrys();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  fetchCountrys = () => {
    this._countryService.getAll().subscribe(
      (data: Country[]) => this.countrysData = data,
      error => console.error(error));
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }
  }

  getNewForm = () => {
    return {
      code: ['', Validators.required ],
      countryCode: ['', Validators.required ],
      firstName: [''],
      lastName: [''],
      login: ['', Validators.required ],
      password: [''],
      age: [''],
      city: [''],
      zipCode: [''],
      phone: [''],
      reviewer: ['']
    };
  }

  load = () => {
    this._customerService.getSingle(this.ids).subscribe(
      (customer: Customer) => {
        this.customer = customer;
        this.form.setValue({
          code: customer.code,
          countryCode: customer.countryCode,
          firstName: customer.firstName,
          lastName: customer.lastName,
          login: customer.login,
          password: customer.password,
          age: customer.age,
          city: customer.city,
          zipCode: customer.zipCode,
          phone: customer.phone,
          reviewer: customer.reviewer
        });
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  save = () => {
	// If we didn't get a customer, we are adding a customer
    if (!this.customer) {
      this.add();
    } else { // If we didn't get a customer, we are adding a customer
      this.update();
    }
  }

  add = () => {
    this._customerService.add(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Customer added successfuly');
        this._router.navigate(['./customer-form', this.form.value.code]);
      },
      error => {
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
    this._customerService.update(<Customer>this.form.getRawValue(), this.ids).subscribe(
      result => this._notificationService.success('Success', 'Customer edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  openDeleteModal = () => {
    this.deleteModal.open();
  }

  confirmDelete = (): void => {
    // Call delete service
    this._customerService.delete(this.customer.code).subscribe(
      result => {
        this._router.navigate(['./customer-list']);

        this._notificationService.success(
          'Deleted',
          `The customer entry with the id(s)='${this.customer.code}' was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });

    this.deleteModal.close();
  }
}
