// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:43 )

// Modules imports
import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { EmployeeGroupService } from './../services/employeeGroup.service';

// Models imports
import { EmployeeGroup } from '../employeeGroup.model';

@Component({
  selector: 'app-employeeGroup-list',
  templateUrl: './employeeGroup-list.component.html',
  styleUrls: ['./employeeGroup-list.component.css']
})
export class EmployeeGroupListComponent implements OnInit {

  @ViewChild('deleteModal') deleteModal;
  private employeeCodeToDelete: string;
  private groupIdToDelete: number;

  private employeeGroupIdToDelete;

  private listOfEmployeeGroups: EmployeeGroup[];
  private listId = 'EMPLOYEEGROUP_COMPONENT_LIST';

  private title = 'List of EmployeeGroups';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _employeeGroupService: EmployeeGroupService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService) { }

  ngOnInit() {
    // On init get all EmployeeGroups
    this.getAllEmployeeGroups();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh EmployeeGroup list
    EmitterService.get(this.listId).subscribe((data: EmployeeGroup[]) => this.getAllEmployeeGroups());
  }

  /**
   * Get all EmployeeGroup using the service EmployeeGroupService
   */
  getAllEmployeeGroups = (): void => {
    this._employeeGroupService.getAll().subscribe(
      (data: EmployeeGroup[]) => {
        this.listOfEmployeeGroups = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editEmployeeGroup = (employeeCode, groupId): void => {
    // Navigate to employeeGroup form component
    this._router.navigate(['./employeeGroup-form', employeeCode, groupId]);
  }

  openDeleteModal(employeeCode, groupId) {
    this.employeeCodeToDelete = employeeCode;
    this.groupIdToDelete = groupId;
    this.deleteModal.open();
  }

  confirmDelete() {
    this._employeeGroupService.delete(this.employeeCodeToDelete, this.groupIdToDelete).subscribe(
      result => {
        // Notify EmployeeGroup list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The car employeeGroup with the id='${this.employeeCodeToDelete}, ${this.groupIdToDelete}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });

    this.deleteModal.close();
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfEmployeeGroups.length, page);

    // get current page of items
    this.pagedItems = this.listOfEmployeeGroups.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
