// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

// Modules imports
import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { BadgeService } from './../services/badge.service';

// Models imports
import { Badge } from '../badge.model';

@Component({
  selector: 'app-badge-list',
  templateUrl: './badge-list.component.html',
  styleUrls: ['./badge-list.component.css']
})
export class BadgeListComponent implements OnInit {

  @ViewChild('deleteModal') deleteModal;
  private badgeNumberToDelete: number;

  private badgeIdToDelete;

  private listOfBadges: Badge[];
  private listId = 'BADGE_COMPONENT_LIST';

  private title = 'List of Badges';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _badgeService: BadgeService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService) { }

  ngOnInit() {
    // On init get all Badges
    this.getAllBadges();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Badge list
    EmitterService.get(this.listId).subscribe((data: Badge[]) => this.getAllBadges());
  }

  /**
   * Get all Badge using the service BadgeService
   */
  getAllBadges = (): void => {
    this._badgeService.getAll().subscribe(
      (data: Badge[]) => {
        this.listOfBadges = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editBadge = (badgeNumber): void => {
    // Navigate to badge form component
    this._router.navigate(['./badge-form', badgeNumber]);
  }

  openDeleteModal(badgeNumber) {
    this.badgeNumberToDelete = badgeNumber;
    this.deleteModal.open();
  }

  confirmDelete() {
    this._badgeService.delete(this.badgeNumberToDelete).subscribe(
      result => {
        // Notify Badge list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The car badge with the id='${this.badgeNumberToDelete}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });

    this.deleteModal.close();
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfBadges.length, page);

    // get current page of items
    this.pagedItems = this.listOfBadges.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
