// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:43 )

export interface Review {
	customerCode: string; // Wrapper Type : String
	bookId: number; // Wrapper Type : Number
	reviewText: string; // Wrapper Type : String
	reviewNote: number; // Wrapper Type : Number
	creation: Date; // Wrapper Type : Date
	lastUpdate: Date; // Wrapper Type : Date
}
