// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

export interface Employee {
	code: string; // Wrapper Type : String
	shopCode: string; // Wrapper Type : String
	firstName: string; // Wrapper Type : String
	lastName: string; // Wrapper Type : String
	manager: number; // Wrapper Type : Number
	badgeNumber: number; // Wrapper Type : Number
	email: string; // Wrapper Type : String
}
