// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:43 )

// Modules imports
import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { PublisherService } from './../services/publisher.service';

// Models imports
import { Publisher } from '../publisher.model';

@Component({
  selector: 'app-publisher-list',
  templateUrl: './publisher-list.component.html',
  styleUrls: ['./publisher-list.component.css']
})
export class PublisherListComponent implements OnInit {

  @ViewChild('deleteModal') deleteModal;
  private codeToDelete: number;

  private publisherIdToDelete;

  private listOfPublishers: Publisher[];
  private listId = 'PUBLISHER_COMPONENT_LIST';

  private title = 'List of Publishers';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _publisherService: PublisherService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService) { }

  ngOnInit() {
    // On init get all Publishers
    this.getAllPublishers();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Publisher list
    EmitterService.get(this.listId).subscribe((data: Publisher[]) => this.getAllPublishers());
  }

  /**
   * Get all Publisher using the service PublisherService
   */
  getAllPublishers = (): void => {
    this._publisherService.getAll().subscribe(
      (data: Publisher[]) => {
        this.listOfPublishers = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editPublisher = (code): void => {
    // Navigate to publisher form component
    this._router.navigate(['./publisher-form', code]);
  }

  openDeleteModal(code) {
    this.codeToDelete = code;
    this.deleteModal.open();
  }

  confirmDelete() {
    this._publisherService.delete(this.codeToDelete).subscribe(
      result => {
        // Notify Publisher list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The car publisher with the id='${this.codeToDelete}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });

    this.deleteModal.close();
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfPublishers.length, page);

    // get current page of items
    this.pagedItems = this.listOfPublishers.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
