// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

// Modules imports
import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { BookOrderService } from './../services/bookOrder.service';

// Models imports
import { BookOrder } from '../bookOrder.model';

@Component({
  selector: 'app-bookOrder-list',
  templateUrl: './bookOrder-list.component.html',
  styleUrls: ['./bookOrder-list.component.css']
})
export class BookOrderListComponent implements OnInit {

  @ViewChild('deleteModal') deleteModal;
  private idToDelete: number;

  private bookOrderIdToDelete;

  private listOfBookOrders: BookOrder[];
  private listId = 'BOOKORDER_COMPONENT_LIST';

  private title = 'List of BookOrders';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _bookOrderService: BookOrderService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService) { }

  ngOnInit() {
    // On init get all BookOrders
    this.getAllBookOrders();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh BookOrder list
    EmitterService.get(this.listId).subscribe((data: BookOrder[]) => this.getAllBookOrders());
  }

  /**
   * Get all BookOrder using the service BookOrderService
   */
  getAllBookOrders = (): void => {
    this._bookOrderService.getAll().subscribe(
      (data: BookOrder[]) => {
        this.listOfBookOrders = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editBookOrder = (id): void => {
    // Navigate to bookOrder form component
    this._router.navigate(['./bookOrder-form', id]);
  }

  openDeleteModal(id) {
    this.idToDelete = id;
    this.deleteModal.open();
  }

  confirmDelete() {
    this._bookOrderService.delete(this.idToDelete).subscribe(
      result => {
        // Notify BookOrder list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The car bookOrder with the id='${this.idToDelete}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });

    this.deleteModal.close();
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfBookOrders.length, page);

    // get current page of items
    this.pagedItems = this.listOfBookOrders.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
