// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:43 )

export interface Shop {
	code: string; // Wrapper Type : String
	name: string; // Wrapper Type : String
	address1: string; // Wrapper Type : String
	address2: string; // Wrapper Type : String
	zipCode: number; // Wrapper Type : Number
	city: string; // Wrapper Type : String
	countryCode: string; // Wrapper Type : String
	phone: string; // Wrapper Type : String
	email: string; // Wrapper Type : String
	executive: string; // Wrapper Type : String
}
