// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:43 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit, ViewChild } from '@angular/core';

// Models and services imports
import { Workgroup } from './../workgroup.model';
import { WorkgroupService } from './../services/workgroup.service';
import * as _ from 'underscore';
import { BsDatepickerConfig } from 'ngx-bootstrap/datepicker';

@Component({
  selector: 'app-workgroup-form',
  templateUrl: './workgroup-form.component.html',
  styleUrls: ['./workgroup-form.component.css']
})
export class WorkgroupFormComponent implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  @ViewChild('deleteModal') deleteModal;

  private title = 'Workgroup Form';
  private workgroup: Workgroup;
  private form: FormGroup;
  private ids;

  private bsConfig: Partial<BsDatepickerConfig>;

  constructor(
    private _workgroupService: WorkgroupService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService) {

    this.bsConfig = Object.assign({}, { containerClass: 'theme-dark-blue' });
  }

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }
  }

  getNewForm = () => {
    return {
      id: ['', Validators.required ],
      name: ['', Validators.required ],
      description: ['', Validators.required ],
      creationDate: ['', Validators.required ]
    };
  }

  load = () => {
    this._workgroupService.getSingle(this.ids).subscribe(
      (workgroup: Workgroup) => {
        this.workgroup = workgroup;
        this.form.setValue({
          id: workgroup.id,
          name: workgroup.name,
          description: workgroup.description,
          creationDate: workgroup.creationDate
        });
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  save = () => {
	// If we didn't get a workgroup, we are adding a workgroup
    if (!this.workgroup) {
      this.add();
    } else { // If we didn't get a workgroup, we are adding a workgroup
      this.update();
    }
  }

  add = () => {
    this._workgroupService.add(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Workgroup added successfuly');
        this._router.navigate(['./workgroup-form', this.form.value.id]);
      },
      error => {
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
    this._workgroupService.update(<Workgroup>this.form.getRawValue(), this.ids).subscribe(
      result => this._notificationService.success('Success', 'Workgroup edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  openDeleteModal = () => {
    this.deleteModal.open();
  }

  confirmDelete = (): void => {
    // Call delete service
    this._workgroupService.delete(this.workgroup.id).subscribe(
      result => {
        this._router.navigate(['./workgroup-list']);

        this._notificationService.success(
          'Deleted',
          `The workgroup entry with the id(s)='${this.workgroup.id}' was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });

    this.deleteModal.close();
  }
}
