// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

// Modules imports
import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { BookOrderItemService } from './../services/bookOrderItem.service';

// Models imports
import { BookOrderItem } from '../bookOrderItem.model';

@Component({
  selector: 'app-bookOrderItem-list',
  templateUrl: './bookOrderItem-list.component.html',
  styleUrls: ['./bookOrderItem-list.component.css']
})
export class BookOrderItemListComponent implements OnInit {

  @ViewChild('deleteModal') deleteModal;
  private bookOrderIdToDelete: number;
  private bookIdToDelete: number;

  private bookOrderItemIdToDelete;

  private listOfBookOrderItems: BookOrderItem[];
  private listId = 'BOOKORDERITEM_COMPONENT_LIST';

  private title = 'List of BookOrderItems';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _bookOrderItemService: BookOrderItemService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService) { }

  ngOnInit() {
    // On init get all BookOrderItems
    this.getAllBookOrderItems();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh BookOrderItem list
    EmitterService.get(this.listId).subscribe((data: BookOrderItem[]) => this.getAllBookOrderItems());
  }

  /**
   * Get all BookOrderItem using the service BookOrderItemService
   */
  getAllBookOrderItems = (): void => {
    this._bookOrderItemService.getAll().subscribe(
      (data: BookOrderItem[]) => {
        this.listOfBookOrderItems = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editBookOrderItem = (bookOrderId, bookId): void => {
    // Navigate to bookOrderItem form component
    this._router.navigate(['./bookOrderItem-form', bookOrderId, bookId]);
  }

  openDeleteModal(bookOrderId, bookId) {
    this.bookOrderIdToDelete = bookOrderId;
    this.bookIdToDelete = bookId;
    this.deleteModal.open();
  }

  confirmDelete() {
    this._bookOrderItemService.delete(this.bookOrderIdToDelete, this.bookIdToDelete).subscribe(
      result => {
        // Notify BookOrderItem list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The car bookOrderItem with the id='${this.bookOrderIdToDelete}, ${this.bookIdToDelete}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });

    this.deleteModal.close();
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfBookOrderItems.length, page);

    // get current page of items
    this.pagedItems = this.listOfBookOrderItems.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
