// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:43 )

export interface Synopsis {
	bookId: number; // Wrapper Type : Number
	synopsis: string; // Wrapper Type : String
}
