// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit, ViewChild } from '@angular/core';

// Models and services imports
import { Bookauthor } from './../bookauthor.model';
import { BookauthorService } from './../services/bookauthor.service';
import * as _ from 'underscore';
import { BsDatepickerConfig } from 'ngx-bootstrap/datepicker';

@Component({
  selector: 'app-bookauthor-form',
  templateUrl: './bookauthor-form.component.html',
  styleUrls: ['./bookauthor-form.component.css']
})
export class BookauthorFormComponent implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  @ViewChild('deleteModal') deleteModal;

  private title = 'Bookauthor Form';
  private bookauthor: Bookauthor;
  private form: FormGroup;
  private ids;

  private bsConfig: Partial<BsDatepickerConfig>;

  constructor(
    private _bookauthorService: BookauthorService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService) {

    this.bsConfig = Object.assign({}, { containerClass: 'theme-dark-blue' });
  }

  ngOnInit() {
    this.getIdFromRouteParams();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }
  }

  getNewForm = () => {
    return {
      title: [''],
      price: [''],
      firstName: [''],
      lastName: ['']
    };
  }

  load = () => {
    this._bookauthorService.getSingle(this.ids).subscribe(
      (bookauthor: Bookauthor) => {
        this.bookauthor = bookauthor;
        this.form.setValue({
          title: bookauthor.title,
          price: bookauthor.price,
          firstName: bookauthor.firstName,
          lastName: bookauthor.lastName
        });
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  save = () => {
	// If we didn't get a bookauthor, we are adding a bookauthor
    if (!this.bookauthor) {
      this.add();
    } else { // If we didn't get a bookauthor, we are adding a bookauthor
      this.update();
    }
  }

  add = () => {
    this._bookauthorService.add(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Bookauthor added successfuly');
        this._router.navigate(['./bookauthor-form', ]);
      },
      error => {
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
    this._bookauthorService.update(<Bookauthor>this.form.getRawValue(), this.ids).subscribe(
      result => this._notificationService.success('Success', 'Bookauthor edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  openDeleteModal = () => {
    this.deleteModal.open();
  }

  confirmDelete = (): void => {
    // Call delete service
    this._bookauthorService.delete().subscribe(
      result => {
        this._router.navigate(['./bookauthor-list']);

        this._notificationService.success(
          'Deleted',
          `The bookauthor entry with the id(s)='' was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });

    this.deleteModal.close();
  }
}
