// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:43 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit, ViewChild } from '@angular/core';

// Models and services imports
import { Publisher } from './../publisher.model';
import { PublisherService } from './../services/publisher.service';
import { Country } from './../../country/country.model';
import { CountryService } from './../../country/services/country.service';
import * as _ from 'underscore';
import { BsDatepickerConfig } from 'ngx-bootstrap/datepicker';

@Component({
  selector: 'app-publisher-form',
  templateUrl: './publisher-form.component.html',
  styleUrls: ['./publisher-form.component.css']
})
export class PublisherFormComponent implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  @ViewChild('deleteModal') deleteModal;

  private title = 'Publisher Form';
  private publisher: Publisher;
  private form: FormGroup;
  private ids;

  private bsConfig: Partial<BsDatepickerConfig>;

  // Country Select
  private countrysData: Country[];

  constructor(
    private _countryService: CountryService,
    private _publisherService: PublisherService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService) {

    this.bsConfig = Object.assign({}, { containerClass: 'theme-dark-blue' });
  }

  ngOnInit() {
    this.getIdFromRouteParams();
    this.fetchCountrys();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  fetchCountrys = () => {
    this._countryService.getAll().subscribe(
      (data: Country[]) => this.countrysData = data,
      error => console.error(error));
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }
  }

  getNewForm = () => {
    return {
      code: ['', Validators.required ],
      countryCode: ['', Validators.required ],
      name: [''],
      email: [''],
      contact: [''],
      city: [''],
      zipCode: [''],
      phone: ['']
    };
  }

  load = () => {
    this._publisherService.getSingle(this.ids).subscribe(
      (publisher: Publisher) => {
        this.publisher = publisher;
        this.form.setValue({
          code: publisher.code,
          countryCode: publisher.countryCode,
          name: publisher.name,
          email: publisher.email,
          contact: publisher.contact,
          city: publisher.city,
          zipCode: publisher.zipCode,
          phone: publisher.phone
        });
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  save = () => {
	// If we didn't get a publisher, we are adding a publisher
    if (!this.publisher) {
      this.add();
    } else { // If we didn't get a publisher, we are adding a publisher
      this.update();
    }
  }

  add = () => {
    this._publisherService.add(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Publisher added successfuly');
        this._router.navigate(['./publisher-form', this.form.value.code]);
      },
      error => {
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
    this._publisherService.update(<Publisher>this.form.getRawValue(), this.ids).subscribe(
      result => this._notificationService.success('Success', 'Publisher edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  openDeleteModal = () => {
    this.deleteModal.open();
  }

  confirmDelete = (): void => {
    // Call delete service
    this._publisherService.delete(this.publisher.code).subscribe(
      result => {
        this._router.navigate(['./publisher-list']);

        this._notificationService.success(
          'Deleted',
          `The publisher entry with the id(s)='${this.publisher.code}' was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });

    this.deleteModal.close();
  }
}
