// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

// Modules imports
import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';

// Services imports
import { PagerService } from './../../../services/pager.service';
import { EmitterService } from './../../../services/emitter.service';
import { NotificationService } from './../../../services/notification.service';
import { AuthorService } from './../services/author.service';

// Models imports
import { Author } from '../author.model';

@Component({
  selector: 'app-author-list',
  templateUrl: './author-list.component.html',
  styleUrls: ['./author-list.component.css']
})
export class AuthorListComponent implements OnInit {

  @ViewChild('deleteModal') deleteModal;
  private idToDelete: number;

  private authorIdToDelete;

  private listOfAuthors: Author[];
  private listId = 'AUTHOR_COMPONENT_LIST';

  private title = 'List of Authors';

  // pager object
  private pager: any = {};
  // paged items
  private pagedItems: any[];

  constructor(
    private _authorService: AuthorService,
    private _router: Router,
    private _notificationService: NotificationService,
    private pagerService: PagerService) { }

  ngOnInit() {
    // On init get all Authors
    this.getAllAuthors();

    // Listen to the 'list' emitted event so as populate the model with the event payload
    // Refresh Author list
    EmitterService.get(this.listId).subscribe((data: Author[]) => this.getAllAuthors());
  }

  /**
   * Get all Author using the service AuthorService
   */
  getAllAuthors = (): void => {
    this._authorService.getAll().subscribe(
      (data: Author[]) => {
        this.listOfAuthors = data;
        this.setPage(1);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
    });
  }

  editAuthor = (id): void => {
    // Navigate to author form component
    this._router.navigate(['./author-form', id]);
  }

  openDeleteModal(id) {
    this.idToDelete = id;
    this.deleteModal.open();
  }

  confirmDelete() {
    this._authorService.delete(this.idToDelete).subscribe(
      result => {
        // Notify Author list to refresh
        EmitterService.get(this.listId).emit(result);

        this._notificationService.success(
          'Deleted',
          `The car author with the id='${this.idToDelete}' was deleted successfuly`);
      },
      error => {
        this._notificationService.error(
          'Error',
          'An error occured when trying to reach the server');
      });

    this.deleteModal.close();
  }

  setPage(page: number) {
    if (page < 1 || page > this.pager.totalPages) {
      return;
    }

    // get pager object from service
    this.pager = this.pagerService.getPager(this.listOfAuthors.length, page);

    // get current page of items
    this.pagedItems = this.listOfAuthors.slice(this.pager.startIndex, this.pager.endIndex + 1);
  }
}
