// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:43 )

import { NotificationService } from './services/notification.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  public _opened = false;
  public title: String = 'Home';

  public navigation = [
		{ title: 'Author', routerLink: 'author-list' },
		{ title: 'Badge', routerLink: 'badge-list' },
		{ title: 'Book', routerLink: 'book-list' },
		{ title: 'BookOrder', routerLink: 'bookOrder-list' },
		{ title: 'BookOrderItem', routerLink: 'bookOrderItem-list' },
		{ title: 'Bookauthor', routerLink: 'bookauthor-list' },
		{ title: 'Country', routerLink: 'country-list' },
		{ title: 'Customer', routerLink: 'customer-list' },
		{ title: 'Employee', routerLink: 'employee-list' },
		{ title: 'EmployeeGroup', routerLink: 'employeeGroup-list' },
		{ title: 'Publisher', routerLink: 'publisher-list' },
		{ title: 'Review', routerLink: 'review-list' },
		{ title: 'Shop', routerLink: 'shop-list' },
		{ title: 'Synopsis', routerLink: 'synopsis-list' },
		{ title: 'Workgroup', routerLink: 'workgroup-list' }
  ];

  public optionsForNotifications = {
    position: ['bottom', 'left'],
    timeOut: 5000,
    lastOnBottom: true,
    showProgressBar: false,
    pauseOnHover: false,
    clickToClose: true,
    preventDuplicates: true
  };

  constructor(
    private _notificationService: NotificationService) { }

  ngOnInit() {
    this._notificationService.init();
  }

  private _toggleOpened(): void {
    this._opened = !this._opened;
  }
}
