// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit, ViewChild } from '@angular/core';

// Models and services imports
import { BookOrder } from './../bookOrder.model';
import { BookOrderService } from './../services/bookOrder.service';
import { Shop } from './../../shop/shop.model';
import { ShopService } from './../../shop/services/shop.service';
import { Customer } from './../../customer/customer.model';
import { CustomerService } from './../../customer/services/customer.service';
import { Employee } from './../../employee/employee.model';
import { EmployeeService } from './../../employee/services/employee.service';
import * as _ from 'underscore';
import { BsDatepickerConfig } from 'ngx-bootstrap/datepicker';

@Component({
  selector: 'app-bookOrder-form',
  templateUrl: './bookOrder-form.component.html',
  styleUrls: ['./bookOrder-form.component.css']
})
export class BookOrderFormComponent implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  @ViewChild('deleteModal') deleteModal;

  private title = 'BookOrder Form';
  private bookOrder: BookOrder;
  private form: FormGroup;
  private ids;

  private bsConfig: Partial<BsDatepickerConfig>;

  // Shop Select
  private shopsData: Shop[];

  // Customer Select
  private customersData: Customer[];

  // Employee Select
  private employeesData: Employee[];

  constructor(
    private _shopService: ShopService,
    private _customerService: CustomerService,
    private _employeeService: EmployeeService,
    private _bookOrderService: BookOrderService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService) {

    this.bsConfig = Object.assign({}, { containerClass: 'theme-dark-blue' });
  }

  ngOnInit() {
    this.getIdFromRouteParams();
    this.fetchShops();
    this.fetchCustomers();
    this.fetchEmployees();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  fetchShops = () => {
    this._shopService.getAll().subscribe(
      (data: Shop[]) => this.shopsData = data,
      error => console.error(error));
  }

  fetchCustomers = () => {
    this._customerService.getAll().subscribe(
      (data: Customer[]) => this.customersData = data,
      error => console.error(error));
  }

  fetchEmployees = () => {
    this._employeeService.getAll().subscribe(
      (data: Employee[]) => this.employeesData = data,
      error => console.error(error));
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }
  }

  getNewForm = () => {
    return {
      id: ['', Validators.required ],
      shopCode: ['', Validators.required ],
      customerCode: ['', Validators.required ],
      employeeCode: ['', Validators.required ],
      date: [''],
      state: ['']
    };
  }

  load = () => {
    this._bookOrderService.getSingle(this.ids).subscribe(
      (bookOrder: BookOrder) => {
        this.bookOrder = bookOrder;
        this.form.setValue({
          id: bookOrder.id,
          shopCode: bookOrder.shopCode,
          customerCode: bookOrder.customerCode,
          employeeCode: bookOrder.employeeCode,
          date: bookOrder.date,
          state: bookOrder.state
        });
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  save = () => {
	// If we didn't get a bookOrder, we are adding a bookOrder
    if (!this.bookOrder) {
      this.add();
    } else { // If we didn't get a bookOrder, we are adding a bookOrder
      this.update();
    }
  }

  add = () => {
    this._bookOrderService.add(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'BookOrder added successfuly');
        this._router.navigate(['./bookOrder-form', this.form.value.id]);
      },
      error => {
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
    this._bookOrderService.update(<BookOrder>this.form.getRawValue(), this.ids).subscribe(
      result => this._notificationService.success('Success', 'BookOrder edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  openDeleteModal = () => {
    this.deleteModal.open();
  }

  confirmDelete = (): void => {
    // Call delete service
    this._bookOrderService.delete(this.bookOrder.id).subscribe(
      result => {
        this._router.navigate(['./bookOrder-list']);

        this._notificationService.success(
          'Deleted',
          `The bookOrder entry with the id(s)='${this.bookOrder.id}' was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });

    this.deleteModal.close();
  }
}
