// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

export interface BookOrder {
	id: number; // Wrapper Type : Number
	shopCode: string; // Wrapper Type : String
	customerCode: string; // Wrapper Type : String
	employeeCode: string; // Wrapper Type : String
	date: Date; // Wrapper Type : Date
	state: number; // Wrapper Type : Number
}
