// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit, ViewChild } from '@angular/core';

// Models and services imports
import { Book } from './../book.model';
import { BookService } from './../services/book.service';
import { Publisher } from './../../publisher/publisher.model';
import { PublisherService } from './../../publisher/services/publisher.service';
import { Author } from './../../author/author.model';
import { AuthorService } from './../../author/services/author.service';
import * as _ from 'underscore';
import { BsDatepickerConfig } from 'ngx-bootstrap/datepicker';

@Component({
  selector: 'app-book-form',
  templateUrl: './book-form.component.html',
  styleUrls: ['./book-form.component.css']
})
export class BookFormComponent implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  @ViewChild('deleteModal') deleteModal;

  private title = 'Book Form';
  private book: Book;
  private form: FormGroup;
  private ids;

  private bsConfig: Partial<BsDatepickerConfig>;

  // Publisher Select
  private publishersData: Publisher[];

  // Author Select
  private authorsData: Author[];

  constructor(
    private _publisherService: PublisherService,
    private _authorService: AuthorService,
    private _bookService: BookService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService) {

    this.bsConfig = Object.assign({}, { containerClass: 'theme-dark-blue' });
  }

  ngOnInit() {
    this.getIdFromRouteParams();
    this.fetchPublishers();
    this.fetchAuthors();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  fetchPublishers = () => {
    this._publisherService.getAll().subscribe(
      (data: Publisher[]) => this.publishersData = data,
      error => console.error(error));
  }

  fetchAuthors = () => {
    this._authorService.getAll().subscribe(
      (data: Author[]) => this.authorsData = data,
      error => console.error(error));
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }
  }

  getNewForm = () => {
    return {
      id: ['', Validators.required ],
      publisherId: ['', Validators.required ],
      authorId: ['', Validators.required ],
      isbn: ['', Validators.required ],
      title: [''],
      price: [''],
      quantity: [''],
      discount: [''],
      availability: [''],
      bestSeller: ['']
    };
  }

  load = () => {
    this._bookService.getSingle(this.ids).subscribe(
      (book: Book) => {
        this.book = book;
        this.form.setValue({
          id: book.id,
          publisherId: book.publisherId,
          authorId: book.authorId,
          isbn: book.isbn,
          title: book.title,
          price: book.price,
          quantity: book.quantity,
          discount: book.discount,
          availability: book.availability,
          bestSeller: book.bestSeller
        });
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  save = () => {
	// If we didn't get a book, we are adding a book
    if (!this.book) {
      this.add();
    } else { // If we didn't get a book, we are adding a book
      this.update();
    }
  }

  add = () => {
    this._bookService.add(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'Book added successfuly');
        this._router.navigate(['./book-form', this.form.value.id]);
      },
      error => {
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
    this._bookService.update(<Book>this.form.getRawValue(), this.ids).subscribe(
      result => this._notificationService.success('Success', 'Book edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  openDeleteModal = () => {
    this.deleteModal.open();
  }

  confirmDelete = (): void => {
    // Call delete service
    this._bookService.delete(this.book.id).subscribe(
      result => {
        this._router.navigate(['./book-list']);

        this._notificationService.success(
          'Deleted',
          `The book entry with the id(s)='${this.book.id}' was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });

    this.deleteModal.close();
  }
}
