// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

export interface Customer {
	code: string; // Wrapper Type : String
	countryCode: string; // Wrapper Type : String
	firstName: string; // Wrapper Type : String
	lastName: string; // Wrapper Type : String
	login: string; // Wrapper Type : String
	password: string; // Wrapper Type : String
	age: number; // Wrapper Type : Number
	city: string; // Wrapper Type : String
	zipCode: number; // Wrapper Type : Number
	phone: string; // Wrapper Type : String
	reviewer: number; // Wrapper Type : Number
}
