// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:43 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit, ViewChild } from '@angular/core';

// Models and services imports
import { EmployeeGroup } from './../employeeGroup.model';
import { EmployeeGroupService } from './../services/employeeGroup.service';
import { Employee } from './../../employee/employee.model';
import { EmployeeService } from './../../employee/services/employee.service';
import { Workgroup } from './../../workgroup/workgroup.model';
import { WorkgroupService } from './../../workgroup/services/workgroup.service';
import * as _ from 'underscore';
import { BsDatepickerConfig } from 'ngx-bootstrap/datepicker';

@Component({
  selector: 'app-employeeGroup-form',
  templateUrl: './employeeGroup-form.component.html',
  styleUrls: ['./employeeGroup-form.component.css']
})
export class EmployeeGroupFormComponent implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  @ViewChild('deleteModal') deleteModal;

  private title = 'EmployeeGroup Form';
  private employeeGroup: EmployeeGroup;
  private form: FormGroup;
  private ids;

  private bsConfig: Partial<BsDatepickerConfig>;

  // Employee Select
  private employeesData: Employee[];

  // Workgroup Select
  private workgroupsData: Workgroup[];

  constructor(
    private _employeeService: EmployeeService,
    private _workgroupService: WorkgroupService,
    private _employeeGroupService: EmployeeGroupService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService) {

    this.bsConfig = Object.assign({}, { containerClass: 'theme-dark-blue' });
  }

  ngOnInit() {
    this.getIdFromRouteParams();
    this.fetchEmployees();
    this.fetchWorkgroups();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  fetchEmployees = () => {
    this._employeeService.getAll().subscribe(
      (data: Employee[]) => this.employeesData = data,
      error => console.error(error));
  }

  fetchWorkgroups = () => {
    this._workgroupService.getAll().subscribe(
      (data: Workgroup[]) => this.workgroupsData = data,
      error => console.error(error));
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }
  }

  getNewForm = () => {
    return {
      employeeCode: ['', Validators.required ],
      groupId: ['', Validators.required ]
    };
  }

  load = () => {
    this._employeeGroupService.getSingle(this.ids).subscribe(
      (employeeGroup: EmployeeGroup) => {
        this.employeeGroup = employeeGroup;
        this.form.setValue({
          employeeCode: employeeGroup.employeeCode,
          groupId: employeeGroup.groupId
        });
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  save = () => {
	// If we didn't get a employeeGroup, we are adding a employeeGroup
    if (!this.employeeGroup) {
      this.add();
    } else { // If we didn't get a employeeGroup, we are adding a employeeGroup
      this.update();
    }
  }

  add = () => {
    this._employeeGroupService.add(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'EmployeeGroup added successfuly');
        this._router.navigate(['./employeeGroup-form', this.form.value.employeeCode, this.form.value.groupId]);
      },
      error => {
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
    this._employeeGroupService.update(<EmployeeGroup>this.form.getRawValue(), this.ids).subscribe(
      result => this._notificationService.success('Success', 'EmployeeGroup edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  openDeleteModal = () => {
    this.deleteModal.open();
  }

  confirmDelete = (): void => {
    // Call delete service
    this._employeeGroupService.delete(this.employeeGroup.employeeCode, this.employeeGroup.groupId).subscribe(
      result => {
        this._router.navigate(['./employeeGroup-list']);

        this._notificationService.success(
          'Deleted',
          `The employeeGroup entry with the id(s)='${this.employeeGroup.employeeCode}, ${this.employeeGroup.groupId}' was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });

    this.deleteModal.close();
  }
}
