// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

export interface Badge {
	badgeNumber: number; // Wrapper Type : Number
	authorizationLevel: number; // Wrapper Type : Number
	endOfValidity: Date; // Wrapper Type : Date
}
