// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

export interface Book {
	id: number; // Wrapper Type : Number
	publisherId: number; // Wrapper Type : Number
	authorId: number; // Wrapper Type : Number
	isbn: string; // Wrapper Type : String
	title: string; // Wrapper Type : String
	price: number; // Wrapper Type : Number
	quantity: number; // Wrapper Type : Number
	discount: number; // Wrapper Type : Number
	availability: number; // Wrapper Type : Number
	bestSeller: number; // Wrapper Type : Number
}
