// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

// Modules imports
import { NotificationService } from './../../../services/notification.service';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Component, OnInit, ViewChild } from '@angular/core';

// Models and services imports
import { BookOrderItem } from './../bookOrderItem.model';
import { BookOrderItemService } from './../services/bookOrderItem.service';
import { BookOrder } from './../../bookOrder/bookOrder.model';
import { BookOrderService } from './../../bookOrder/services/bookOrder.service';
import { Book } from './../../book/book.model';
import { BookService } from './../../book/services/book.service';
import * as _ from 'underscore';
import { BsDatepickerConfig } from 'ngx-bootstrap/datepicker';

@Component({
  selector: 'app-bookOrderItem-form',
  templateUrl: './bookOrderItem-form.component.html',
  styleUrls: ['./bookOrderItem-form.component.css']
})
export class BookOrderItemFormComponent implements OnInit {

  // HTTP status code
  readonly NOT_FOUND_ERROR = 404;
  readonly CONFLICT_ERROR = 409;
  readonly INTERNAL_SERVER_ERROR = 500;

  @ViewChild('deleteModal') deleteModal;

  private title = 'BookOrderItem Form';
  private bookOrderItem: BookOrderItem;
  private form: FormGroup;
  private ids;

  private bsConfig: Partial<BsDatepickerConfig>;

  // BookOrder Select
  private bookOrdersData: BookOrder[];

  // Book Select
  private booksData: Book[];

  constructor(
    private _bookOrderService: BookOrderService,
    private _bookService: BookService,
    private _bookOrderItemService: BookOrderItemService,
    private _route: ActivatedRoute,
    private _router: Router,
    private _formBuilder: FormBuilder,
    private _notificationService: NotificationService) {

    this.bsConfig = Object.assign({}, { containerClass: 'theme-dark-blue' });
  }

  ngOnInit() {
    this.getIdFromRouteParams();
    this.fetchBookOrders();
    this.fetchBooks();
    this.initForm();
  }

  getIdFromRouteParams = () => {
    this._route.params.subscribe(p => {
        this.ids = _.values(p);
    });
  }

  fetchBookOrders = () => {
    this._bookOrderService.getAll().subscribe(
      (data: BookOrder[]) => this.bookOrdersData = data,
      error => console.error(error));
  }

  fetchBooks = () => {
    this._bookService.getAll().subscribe(
      (data: Book[]) => this.booksData = data,
      error => console.error(error));
  }

  initForm = () => {
    this.form = this._formBuilder.group(this.getNewForm());
    if (!_.isEmpty(this.ids)) {
      this.load();
    }
  }

  getNewForm = () => {
    return {
      bookOrderId: ['', Validators.required ],
      bookId: ['', Validators.required ],
      quantity: ['', Validators.required ],
      price: ['', Validators.required ]
    };
  }

  load = () => {
    this._bookOrderItemService.getSingle(this.ids).subscribe(
      (bookOrderItem: BookOrderItem) => {
        this.bookOrderItem = bookOrderItem;
        this.form.setValue({
          bookOrderId: bookOrderItem.bookOrderId,
          bookId: bookOrderItem.bookId,
          quantity: bookOrderItem.quantity,
          price: bookOrderItem.price
        });
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  save = () => {
	// If we didn't get a bookOrderItem, we are adding a bookOrderItem
    if (!this.bookOrderItem) {
      this.add();
    } else { // If we didn't get a bookOrderItem, we are adding a bookOrderItem
      this.update();
    }
  }

  add = () => {
    this._bookOrderItemService.add(this.form.value).subscribe(
      result => {
        this._notificationService.success('Success', 'BookOrderItem added successfuly');
        this._router.navigate(['./bookOrderItem-form', this.form.value.bookOrderId, this.form.value.bookId]);
      },
      error => {
        if (error.status === this.CONFLICT_ERROR) {
          this._notificationService.error(error.statusText, 'Id already used in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  update = () => {
    this._bookOrderItemService.update(<BookOrderItem>this.form.getRawValue(), this.ids).subscribe(
      result => this._notificationService.success('Success', 'BookOrderItem edited successfuly'),
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });
  }

  openDeleteModal = () => {
    this.deleteModal.open();
  }

  confirmDelete = (): void => {
    // Call delete service
    this._bookOrderItemService.delete(this.bookOrderItem.bookOrderId, this.bookOrderItem.bookId).subscribe(
      result => {
        this._router.navigate(['./bookOrderItem-list']);

        this._notificationService.success(
          'Deleted',
          `The bookOrderItem entry with the id(s)='${this.bookOrderItem.bookOrderId}, ${this.bookOrderItem.bookId}' was deleted successfuly`);
      },
      error => {
        if (error.status === this.NOT_FOUND_ERROR) {
          this._notificationService.error(error.statusText, 'Entity not found in database');
        } else if (error.status === this.INTERNAL_SERVER_ERROR) {
          this._notificationService.error(error.statusText, error.json());
        } else {
          this._notificationService.error('Error', 'An error occured when trying to reach the server');
        }
      });

    this.deleteModal.close();
  }
}
