// File generated by Telosys Tools Generator ( version 3.0.0 ) - Date 2018-01-15 ( Time 16:52:42 )

export interface Bookauthor {
	title: string; // Wrapper Type : String
	price: number; // Wrapper Type : Number
	firstName: string; // Wrapper Type : String
	lastName: string; // Wrapper Type : String
}
